#
# This file contains configuration flags to customize the site
#

name: Shashank Giri

description: 3rd yearite, Computer Science undergrad.


avatar: https://avatars0.githubusercontent.com/u/26007411?s=400&v=4

footer-links:

  email: g.shashank700@gmail.com
  facebook: shashank.giri.779
  github: shashank98giri/
  linkedin : in/shashank-giri-023b5113a/




disqus: shashank98giri-github-io
google_analytics:

url: ""

baseurl: ""

#
#

permalink: /:title/

version: v3.7.3

kramdown:
  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded 

# Use the following plug-ins
gems:
  - jekyll-sitemap
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
